FROM alpine
RUN apk --no-cache add postgresql17-client bash git vim
RUN mkdir /data
COPY inputrc /root/.inputrc
COPY psqlrc /root/.psqlrc
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
